# Package areas
'area: sdk':
  - changed-files:
    - any-glob-to-any-file: 'packages/sdk/**/*'

'area: server':
  - changed-files:
    - any-glob-to-any-file: 'packages/server/**/*'

'area: dashboard':
  - changed-files:
    - any-glob-to-any-file: 'packages/dashboard/**/*'

# Documentation
'documentation':
  - changed-files:
    - any-glob-to-any-file: 
      - '*.md'
      - 'docs/**/*'

# CI/CD
'ci/cd':
  - changed-files:
    - any-glob-to-any-file: '.github/**/*' 