version: '3.8'

services:
  bilan-server:
    build: .
    ports:
      - "3001:3001"
    environment:
      - DB_PATH=/app/data/bilan.db
      - PORT=3001
    volumes:
      - ./data:/app/data
    networks:
      - bilan-network

  bilan-dashboard:
    build: 
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "3004:3004"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://bilan-server:3001
    depends_on:
      - bilan-server
    networks:
      - bilan-network

networks:
  bilan-network:
    driver: bridge

volumes:
  bilan-data: 