name: 🐛 Bug Report
description: Create a report to help us improve Bilan
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report! 🙏
        
        Before submitting, please:
        - Search existing issues to avoid duplicates
        - Try with the latest version of Bilan
        - Include all relevant details below

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues that describe this bug
          required: true
        - label: I am using the latest version of @mocksi/bilan-sdk
          required: true
        - label: I have read the documentation
          required: true

  - type: dropdown
    id: package
    attributes:
      label: Which package is affected?
      multiple: true
      options:
        - "@mocksi/bilan-sdk"
        - "@bilan/server"
        - "@bilan/dashboard"
        - "Examples"
        - "Documentation"
        - "Other"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of the package are you using?
      placeholder: "e.g., 0.3.0"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      multiple: true
      options:
        - "Browser"
        - "Node.js"
        - "Next.js"
        - "React"
        - "Vue"
        - "Other framework"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "Describe the bug..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Tell us how to reproduce this behavior
      placeholder: |
        1. Initialize SDK with...
        2. Call vote() with...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: "I expected..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Instead, this happened..."
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: Please provide a minimal code sample that reproduces the issue
      render: typescript
      placeholder: |
        import { init, vote } from '@mocksi/bilan-sdk'
        
        init({
          mode: 'local',
          userId: 'test-user'
        })
        
        // Bug happens here...

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages
      description: Any error messages or console output
      render: text
      placeholder: "Paste error messages here..."

  - type: textarea
    id: browser-info
    attributes:
      label: Browser/Environment Info
      description: If relevant, please provide browser and system information
      placeholder: |
        - OS: [e.g., macOS 13.0, Windows 11]
        - Browser: [e.g., Chrome 118, Firefox 119]
        - Node.js version: [e.g., 18.17.0]

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: "Any additional information that might be helpful..." 