name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Check Node.js and npm version
        run: |
          node --version
          npm --version

      - name: Clean install
        run: |
          rm -rf node_modules
          npm ci

      - name: Build packages
        run: npm run build

      - name: Test SDK with coverage
        run: cd packages/sdk && npm run test -- --coverage --run

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN || '' }}
          files: ./packages/sdk/coverage/lcov.info
          flags: sdk
          name: sdk-coverage
          fail_ci_if_error: false

      - name: Validate bundle size
        run: |
          BUNDLE_SIZE=$(gzip -c packages/sdk/dist/index.js | wc -c)
          echo "Bundle size: ${BUNDLE_SIZE} bytes gzipped"
          if [ $BUNDLE_SIZE -gt 5632 ]; then
            echo "❌ Bundle size ${BUNDLE_SIZE} bytes exceeds 5.5KB limit"
            exit 1
          else
            echo "✅ Bundle size ${BUNDLE_SIZE} bytes is within 5.5KB limit"
          fi 